---
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
    external: false

services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: ivr_cloudflared
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TOKEN}
    networks:
      backend:
        aliases:
          - cloudflared
      frontend:
    restart: unless-stopped
  flask:
    image: ivr:local
    container_name: ivr_flask
    command: python3 call_handler.py
    environment:
      SLACK_APP_TOKEN: ${SLACK_APP_TOKEN}
      SLACK_BOT_TOKEN: ${SLACK_BOT_TOKEN}
    volumes:
      - ./data:/data
    networks:
      backend:
        aliases:
          - flask
    restart: unless-stopped
